/* Portically Campo Energia — V2 · v1.0.1. Dados locais. Sem analytics ou servidor. */
'use strict';
const VERSION='V2',SEMVER='1.0.1',SCHEMA=1;
const $=s=>document.querySelector(s),E=Core.esc;
const NAV=[['home','Início','home'],['checklist','Roteiro','check'],['map','Mapa / GPS','map'],['evidence','Evidências','camera'],['backup','Backup','archive']];
const ICONS={home:'M3 10 12 3l9 7M5 9v12h14V9M9 21v-8h6v8',check:'M9 5h12M9 12h12M9 19h12M2 5l2 2 3-4M2 12l2 2 3-4M2 19l2 2 3-4',map:'m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5m6-2v16m6-14v16',camera:'M3 7h4l2-3h6l2 3h4v13H3V7m13 6a4 4 0 1 1-8 0 4 4 0 0 1 8 0',archive:'M3 3h18v5H3zM5 8v13h14V8m-10 5h6',gps:'M12 1v4m0 14v4M1 12h4m14 0h4M19 12a7 7 0 1 1-14 0 7 7 0 0 1 14 0m-5 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0',arrow:'M5 12h14m-6-6 6 6-6 6',plus:'M12 4v16M4 12h16',shield:'m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6l8-4m-4 10 3 3 5-6',download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4'};
const icon=k=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${ICONS[k]||ICONS.check}" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const STATUSES={pending:'Não preenchido',done:'Verificado',notfound:'Não identificado',na:'Não se aplica',later:'Verificar depois'};
const KINDS=['Vértice do limite','Referência em campo','Torre anemométrica','Linha elétrica','Subestação','Acesso','Obstáculo','Água / drenagem','Ponto alto','Área solar','Comunidade / edificação','Parque eólico','Usina solar','Interferência','Outro'];
let projects=[],visits=[],evidence=[],audit=[],project,visit,view='home',filter='all',lastGPS=null,mapZoom=1;
let dbReady=false,saveQueue=Promise.resolve(),saveError=null,offlineReady=false,persistent=false,installEvent=null,routeId=null,wakeLock=null,routeBusy=false,routeSegment=null,urls=[];
let recorder=null,recorderStream=null,recordingSection=34,recordingStarted=null,recordingChunks=[],recordingTimeout=null,busy=false,writerRelease=null,readOnly=false;
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
const now=()=>new Date().toISOString();
const fmtDate=s=>s?new Date(s).toLocaleString('pt-BR'):'Não registrado';
const num=(n,d=2)=>Number.isFinite(n)?n.toLocaleString('pt-BR',{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
const bytes=n=>n<1048576?num(n/1024,1)+' KB':num(n/1048576,1)+' MB';
const safeFile=s=>String(s).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,100)||'arquivo';
function toast(s,bad=false){let el=$('#toast');el.textContent=s;el.className='toast show'+(bad?' bad':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',bad?7000:4200);}
function savedStatus(text,bad=false){$('#save-status').textContent=text;$('#save-status').className='save-status'+(bad?' error':'');}
function fail(err){console.error(err);toast(err.message||String(err),true);}
function newVisit(pid,name){return {id:uid(),projectId:pid,name:name||'Vistoria '+new Date().toLocaleDateString('pt-BR'),createdAt:now(),updatedAt:now(),status:'draft',sections:{},points:[],boundary:{pointIds:[],closed:false,source:'field'},boundaryHistory:[],route:[],routeIgnored:0,exportCount:0,lastBackupAt:null,lastBackupUpdatedAt:null};}
function answer(id){return visit.sections[id]||{status:'pending',reason:'',fields:{}};}
function evFor(id){return evidence.filter(e=>e.visitId===visit.id&&e.sectionId===Number(id));}
function checks(s){let a=answer(s.id),errors=[];if(a.status==='pending')errors.push('Etapa ainda não preenchida.');else if(a.status==='done'){
for(const [id,label,type,req] of s.fields)if(req&&!String(a.fields[id]??'').trim())errors.push('Falta: '+label+'.');
if(s.minEvidence&&evFor(s.id).length<s.minEvidence)errors.push('Anexe ao menos '+s.minEvidence+' evidência(s), ou registre a impossibilidade.');
if(s.gps&&!visit.points.some(p=>p.sectionId===s.id))errors.push('Falta um ponto GPS vinculado a esta etapa (medido ou digitado com fonte).');
if(s.id===3&&!visit.boundary.closed)errors.push('O perímetro ainda não foi fechado/conferido.');
}else if(!a.reason?.trim())errors.push('Informe o motivo de “'+STATUSES[a.status]+'”.');
return errors;}
function metrics(){let valid=CHECKLIST.filter(s=>checks(s).length===0),actual=valid.filter(s=>answer(s.id).status==='done');return {addressed:valid.length,verified:actual.length,pending:40-valid.length,issues:CHECKLIST.filter(s=>checks(s).length>0||['later','notfound'].includes(answer(s.id).status))};}
function mutable(){if(readOnly)throw Error('Esta aba está em modo somente leitura. Feche a outra aba do aplicativo e recarregue.');if(busy)throw Error('Aguarde a operação de backup/importação terminar.');if(visit.status==='closed'||visit.status==='closed-pending')throw Error('Reabra a vistoria antes de alterar os dados.');}
function auditEntry(action,detail){const row={id:uid(),visitId:visit.id,at:now(),action,detail:String(detail).slice(0,1000)};audit.push(row);return row;}
function scheduleSave(action,detail){
 if(!dbReady)return Promise.resolve();visit.updatedAt=now();const copy=structuredClone(visit),row=action?auditEntry(action,detail):null;savedStatus('Salvando neste aparelho…');
 saveQueue=saveQueue.catch(()=>{}).then(()=>Store.batch([{store:'visits',value:copy},...(row?[{store:'audit',value:row}]:[])])).then(()=>{saveError=null;savedStatus('Salvo neste aparelho · '+new Date().toLocaleTimeString('pt-BR'));}).catch(e=>{saveError=e;savedStatus('FALHA AO SALVAR — exporte backup',true);toast('Não foi possível salvar: '+e.message,true);throw e;});saveQueue.catch(()=>{});return saveQueue;
}
async function flush(){await saveQueue;if(saveError)throw saveError;}
function coordsText(p){return p?`${Number(p.lat).toFixed(6)}, ${Number(p.lon).toFixed(6)}`:'Sem coordenada';}
function connection(){const on=navigator.onLine;$('#connection').textContent=on?'Rede detectada':'Sem rede · modo campo';$('#connection').className='connection'+(on?'':' off');}
function screenNav(){for(const el of [$('#side-nav'),$('#bottom-nav')])el.innerHTML=NAV.map(([id,label,ic])=>`<button class="nav-item ${view===id?'active':''}" data-nav="${id}" ${view===id?'aria-current="page"':''}>${icon(ic)}<span>${label}</span></button>`).join('');$('#screen-code').textContent='CAM-'+String(NAV.findIndex(n=>n[0]===view)+1).padStart(3,'0')+' · V2';}
function releaseURLs(){for(const u of urls)URL.revokeObjectURL(u);urls=[];}
function blobURL(b){let u=URL.createObjectURL(b);urls.push(u);return u;}
function render(){if(!project||!visit)return;releaseURLs();screenNav();let html=({home:homeView,checklist:checklistView,map:mapView,evidence:evidenceView,backup:backupView}[view]||homeView)();$('#main').innerHTML=(readOnly?'<div class="notice danger">Modo somente leitura: existe outra aba editando este banco. Feche a outra aba e recarregue esta.</div>':'')+(visit.status!=='draft'?'<div class="notice info">Vistoria encerrada. Os dados estão protegidos contra alterações nesta tela. <button class="btn small-btn" data-action="reopen">Reabrir vistoria</button></div>':'')+html;if(view==='backup')refreshStorage();}
async function go(next){if(busy)return toast('Aguarde a operação atual.');try{await flush();}catch(e){fail(e);if(next!=='backup')return;}view=next;render();window.scrollTo({top:0,behavior:'instant'});}
function heroMap(){return mapSVG(true);}
function homeView(){const m=metrics(),n=evidence.filter(e=>e.visitId===visit.id).length;return `
<div class="page-intro row between"><div><div class="eyebrow">Pré-viabilidade · coleta guiada</div><h1>Seu projeto começa no campo.</h1><p class="muted small">Registre os fatos. Guarde as evidências. Volte com menos dúvidas.</p></div></div>
${!Core.valid(project.reference)?'<div class="notice info"><strong>Primeiro acesso:</strong> cadastre o ponto de referência em <button class="btn small-btn" data-action="editProject">Editar projeto</button>. A localização não vem embutida no site público.</div>':''}<div class="header-selects"><label class="field"><span>Propriedade / projeto</span><select id="project-select">${projects.map(p=>`<option value="${E(p.id)}" ${p.id===project.id?'selected':''}>${E(p.name)}</option>`).join('')}</select></label><label class="field"><span>Vistoria neste aparelho</span><select id="visit-select">${visits.filter(v=>v.projectId===project.id).map(v=>`<option value="${E(v.id)}" ${v.id===visit.id?'selected':''}>${E(v.name)}${v.status!=='draft'?' · encerrada':''}</option>`).join('')}</select></label></div>
<section class="hero"><div class="hero-grid"><div><div class="eyebrow">Eólica + solar + híbrida</div><h1>${E(project.name)}</h1><p>${num(project.areaHa,0)} ha de referência · perímetro ${visit.boundary.closed?'coletado e fechado':'a levantar'}</p><div class="row"><span class="pill">${offlineReady?'Aplicativo preparado offline':'Preparar antes de viajar'}</span><span class="pill">${E(visit.name)}</span></div><div class="actions"><button class="btn primary" data-nav="checklist">Continuar roteiro ${icon('arrow')}</button><button class="btn ghost" style="color:#fff;border-color:#ffffff44" data-nav="map">${icon('gps')} Marcar limites</button></div></div><div>${heroMap()}<div class="map-caption">Esquema de referência. Não é limite legal do imóvel.</div></div></div></section>
<div class="grid3"><div class="metric"><div class="metric-header">Etapas tratadas ${icon('check')}</div><div class="metric-number">${m.addressed}<span style="font-size:14px;color:var(--muted)"> / 40</span></div><div class="metric-label">${m.verified} verificadas; demais com justificativa</div></div><div class="metric"><div class="metric-header">Pontos coletados ${icon('gps')}</div><div class="metric-number">${visit.points.length}</div><div class="metric-label">${visit.boundary.pointIds.length} vértices de limite</div></div><div class="metric"><div class="metric-header">Evidências ${icon('camera')}</div><div class="metric-number">${n}</div><div class="metric-label">Arquivos salvos no aparelho</div></div></div>
<div class="grid2"><section class="card"><h2>Uma etapa de cada vez</h2>${[
['01','Prepare o celular','Offline, armazenamento e permissões.','prepare','Preparar'],['02','Mapeie os limites','Vértices, percurso e pontos de interesse.','map','Mapear'],['03','Siga o roteiro','40 etapas com instruções e evidências.','checklist','Coletar'],['04','Confira antes de sair','Encontre lacunas e registre impossibilidades.','review','Conferir']].map(([no,t,d,a,b])=>`<div class="guide-step"><span class="step-no">${no}</span><div><h3>${t}</h3><p>${d}</p></div><button class="btn small-btn" ${['map','checklist'].includes(a)?'data-nav':'data-action'}="${a}">${b}</button></div>`).join('')}</section>
<section class="card"><h2>Proteja o que você coletou</h2><p class="muted small">Esta V2 guarda tudo no navegador deste aparelho. Nenhum dado foi enviado a um servidor.</p><div class="progress"><i style="width:${m.addressed/40*100}%"></i></div><p class="small">${m.pending} etapas sem tratamento completo. ${m.issues.length} etapas ainda exigem atenção.</p><div class="notice">${visit.lastBackupAt?'Último pacote gerado: '+fmtDate(visit.lastBackupAt)+'. Confira o arquivo e guarde uma cópia fora do celular.':'Ainda não há backup gerado desta vistoria.'}</div><button class="btn soft full" data-nav="backup">${icon('archive')} Backup e relatório</button><p class="small muted spaced">O quadrado de ${num(project.areaHa,0)} ha é provisório. O aplicativo não confirma vento, conexão ou viabilidade.</p></section></div>
<div class="actions"><button class="btn" data-action="newVisit">Nova vistoria</button><button class="btn" data-action="editProject">Editar projeto</button><button class="btn" data-action="newProject">Outra propriedade</button><button class="btn" data-action="install">Instalar no celular</button></div>`;}
function checklistView(){const m=metrics();let sections=CHECKLIST.filter(s=>filter==='all'||(filter==='issues'&&(checks(s).length||['notfound','later'].includes(answer(s.id).status)))||(filter==='critical'&&s.critical));let group='';return `<div class="page-intro"><div class="eyebrow">Roteiro de campo · 40 etapas</div><h1>O que coletar, e como.</h1><p class="small muted">Salvamento automático. Quando não souber, registre o motivo em vez de inventar.</p></div><section class="card"><div class="row between"><strong class="small">${m.addressed}/40 etapas tratadas · ${m.verified} verificadas</strong><button class="btn small-btn soft" data-action="review">Posso sair do local?</button></div><div class="progress"><i style="width:${m.addressed/40*100}%"></i></div><select id="check-filter" aria-label="Filtrar etapas"><option value="all" ${filter==='all'?'selected':''}>Todas as etapas</option><option value="issues" ${filter==='issues'?'selected':''}>Com pendências / atenção</option><option value="critical" ${filter==='critical'?'selected':''}>Etapas prioritárias</option></select></section>
${sections.map(s=>{let g=s.group!==group?`<h2 class="group-title">${E(s.group)}</h2>`:'';group=s.group;let a=answer(s.id),errs=checks(s),ok=errs.length===0;return g+`<details class="section" id="section-${s.id}"><summary class="details-summary"><span class="step-no">${String(s.id).padStart(2,'0')}</span><span class="section-title">${E(s.title)}${s.critical?'<br><span class="small muted">Prioritária</span>':''}</span><span class="status-dot ${ok?(a.status==='done'?'ok':'attention'):''}"></span><span class="pill ${ok?(a.status==='done'?'':'warn'):'gray'}" id="tag-${s.id}">${E(STATUSES[a.status])}${a.status==='done'&&errs.length?' · incompleta':''}</span></summary><div class="section-body"><div class="help"><strong>Como fazer</strong><p>${E(s.help)}</p>${s.photos.length?'<strong>O que registrar</strong><ul>'+s.photos.map(p=>'<li>'+E(p)+'</li>').join('')+'</ul>':''}</div>
${s.fields.map(([id,label,type,required])=>`<label class="field"><span>${E(label)}${required?' <span class="muted">*</span>':''}</span>${type==='textarea'?`<textarea data-field="${id}" data-section="${s.id}">${E(a.fields[id]||'')}</textarea>`:`<input type="${type}" data-field="${id}" data-section="${s.id}" value="${E(a.fields[id]||'')}">`}</label>`).join('')}
<label class="field"><span>Situação da etapa</span><select data-section="${s.id}" data-status>${Object.entries(STATUSES).map(([k,t])=>`<option value="${k}" ${a.status===k?'selected':''}>${t}</option>`).join('')}</select></label><label class="field"><span>Justificativa / por que não foi possível obter</span><textarea data-reason data-section="${s.id}" placeholder="Obrigatória para Não identificado, Não se aplica ou Verificar depois.">${E(a.reason)}</textarea></label><div id="validation-${s.id}">${errs.length?'<div class="errors">'+errs.map(E).join('<br>')+'</div>':'<p class="small">Etapa tratada. '+(a.status==='done'?'Evidências e campos mínimos presentes.':'Justificativa registrada; não equivale a dado verificado.')+'</p>'}</div>
<div class="actions"><button class="btn soft" data-action="addEvidence" data-section="${s.id}">${icon('camera')} Anexar evidência (${evFor(s.id).length})</button><button class="btn" data-action="gpsSection" data-section="${s.id}">${icon('gps')} Ponto GPS</button>${s.id===3?'<button class="btn" data-nav="map">Mapear limites</button>':''}<button class="btn" data-action="nextSection" data-section="${s.id}">Próxima etapa ${icon('arrow')}</button></div></div></details>`}).join('')}
<div class="notice info">Você pode salvar e sair a qualquer momento. Encerrar a coleta exige tratar todas as etapas; justificativas permitem registrar o que não foi possível coletar com segurança.</div><div class="actions"><button class="btn primary" data-action="review">Conferir pendências</button><button class="btn" data-action="closeVisit">Encerrar vistoria</button></div>`;}
function mapSVG(mini=false){const origin=Core.valid(project.reference)?project.reference:visit.points.find(Core.valid)||visit.route.find(Core.valid);if(!origin)return '<div class="empty">Localização ainda não cadastrada.<br>Toque em Editar projeto ou capture um ponto GPS.<br>Seus dados ficarão somente neste aparelho.</div>';let boundary=visit.boundary.pointIds.map(id=>visit.points.find(p=>p.id===id)).filter(Boolean),ref=Core.valid(project.reference)?Core.square(project.reference,project.areaHa):[];let ps=[origin,...ref,...visit.points,...visit.route].filter(Core.valid).map(p=>Core.project(p,origin));let minX=Math.min(...ps.map(p=>p.x)),maxX=Math.max(...ps.map(p=>p.x)),minY=Math.min(...ps.map(p=>p.y)),maxY=Math.max(...ps.map(p=>p.y));let width=640,height=mini?300:430;let spanX=Math.max(100,maxX-minX),spanY=Math.max(100,maxY-minY),scale=Math.min((width-85)/spanX,(height-85)/spanY)*(mini?1:mapZoom);let cx=(minX+maxX)/2,cy=(minY+maxY)/2;
const pt=p=>{let q=Core.project(p,origin);return [(q.x-cx)*scale+width/2,height/2-(q.y-cy)*scale];},sps=p=>p.map(pt).map(c=>c.map(n=>n.toFixed(2)).join(',')).join(' '),center=pt(origin);let trackGroups={};visit.route.forEach(p=>(trackGroups[p.segment]??=[]).push(p));
let barMeters=[10,25,50,100,250,500,1000,2000,5000,10000,50000].filter(n=>n*scale<140).pop()||10;
return `<svg class="${mini?'mini-map':'field-map'}" viewBox="0 0 ${width} ${height}" role="img" aria-label="Croqui offline da área de referência e pontos registrados"><defs><pattern id="grid-${mini}" width="35" height="35" patternUnits="userSpaceOnUse"><path d="M35 0H0V35" fill="none" stroke="${mini?'#ffffff0b':'#bccfb540'}" stroke-width="1"/></pattern></defs><rect width="100%" height="100%" fill="url(#grid-${mini})"/><polygon points="${sps(ref)}" fill="${mini?'#b8d39518':'#ecd3a237'}" stroke="${mini?'#c2d88e':'#b78336'}" stroke-dasharray="8 6" stroke-width="2"/>${boundary.length?`<${visit.boundary.closed?'polygon':'polyline'} points="${sps(boundary)}" fill="${visit.boundary.closed?'#84b78945':'none'}" stroke="${mini?'#def1d1':'#285c49'}" stroke-width="3"/>`:''}${Object.values(trackGroups).map(g=>`<polyline points="${sps(g)}" fill="none" stroke="#60819a" stroke-width="2" stroke-dasharray="3 3"/>`).join('')}
<g opacity="${Core.valid(project.reference)?1:0}" transform="translate(${center[0]},${center[1]})"><circle r="7" fill="${mini?'#d2e7b1':'#426547'}"/><circle r="13" fill="none" stroke="${mini?'#d2e7b1':'#426547'}" stroke-opacity=".4"/></g>
${visit.points.map((p,i)=>{let [x,y]=pt(p);return `<circle cx="${x}" cy="${y}" r="5" fill="${p.kind==='Vértice do limite'?'#245a47':'#aa732c'}" stroke="#fff" stroke-width="1.5"/><text x="${x+8}" y="${y-6}" font-size="12" fill="${mini?'#e7f0df':'#234d3c'}">${i+1}</text>`}).join('')}
<text x="${width-33}" y="27" font-size="12" font-weight="700" fill="${mini?'#d0dec4':'#4c6556'}">N</text><path d="M${width-29} 35v30m-5-25 5-9 5 9" stroke="${mini?'#d0dec4':'#4c6556'}" fill="none" stroke-width="2"/>
<path d="M22 ${height-28}v6h${barMeters*scale}v-6" stroke="${mini?'#d0dec4':'#4c6556'}" fill="none" stroke-width="2"/><text x="22" y="${height-32}" font-size="11" fill="${mini?'#d0dec4':'#4c6556'}">${barMeters>=1000?barMeters/1000+' km':barMeters+' m'}</text><text x="${width-22}" y="${height-18}" text-anchor="end" fill="${mini?'#bccfbc':'#6b7e6e'}" font-size="10">CROQUI · SEM SATÉLITE</text></svg>`;}
function mapView(){let b=visit.boundary.pointIds.map(id=>visit.points.find(p=>p.id===id)).filter(Boolean),m=b.length>=3?Core.polygon(b,visit.boundary.closed):{},length=visit.route.reduce((sum,p,i)=>sum+(i&&p.segment===visit.route[i-1].segment?Core.distance(p,visit.route[i-1]):0),0);return `<div class="page-intro"><div class="eyebrow">Limites e pontos de interesse</div><h1>Mapeie a área, sem depender de sinal.</h1><p class="small muted">Croqui offline disponível. Sem imagens de satélite nesta V2.</p></div><section class="card"><div class="row between"><h2>Mapa de campo</h2><span class="pill warn">${num(project.areaHa,0)} ha apenas como referência</span></div>${mapSVG()}<div class="map-toolbar"><div class="row"><button class="btn small-btn" data-action="zoomIn" aria-label="Ampliar mapa">+</button><button class="btn small-btn" data-action="zoomOut" aria-label="Reduzir mapa">−</button><button class="btn small-btn" data-action="zoomFit">Ajustar</button></div><button class="btn small-btn" data-action="externalMap">Mapa online ↗</button></div><div class="map-legend"><span><i class="legend-box"></i>Referência provisória</span><span><i class="legend-box real"></i>Limite coletado</span><span>Tracejado azul: percurso</span></div><div class="map-caption">Centro de referência: ${coordsText(project.reference)}. Não é GPS atual. O quadrado não comprova divisas nem área aproveitável.</div></section>
<div class="grid3"><div class="metric"><div class="metric-header">Vértices</div><div class="metric-number">${b.length}</div><div class="metric-label">${visit.boundary.closed?'Polígono fechado':'Polígono em aberto'}</div></div><div class="metric"><div class="metric-header">Área aproximada</div><div class="metric-number">${visit.boundary.closed&&!m.error?num(m.ha):'—'}</div><div class="metric-label">hectares · não cadastral</div></div><div class="metric"><div class="metric-header">${visit.boundary.closed?'Perímetro':'Percurso registrado'}</div><div class="metric-number">${num((visit.boundary.closed&&!m.error?m.perimeter:length)/1000)}</div><div class="metric-label">km · pontos do celular</div></div></div>
<div class="grid2"><section class="card"><h2>Adicionar ponto</h2><label class="field"><span>Tipo</span><select id="point-kind">${KINDS.map(k=>'<option>'+E(k)+'</option>').join('')}</select></label><label class="field"><span>Nome / observação curta</span><input id="point-label" maxlength="160" placeholder="Ex.: porteira norte, curva da estrada"></label><div class="actions"><button class="btn primary" data-action="capturePoint">${icon('gps')} Capturar GPS</button><button class="btn" data-action="manualPoint">Digitar coordenada</button></div><div class="notice info">${lastGPS?`Última leitura: ${coordsText(lastGPS)} · precisão ±${num(lastGPS.accuracy,0)} m · ${fmtDate(lastGPS.gpsAt)}. Não é rastreamento contínuo.`:'O GPS só será solicitado ao tocar no botão. Localização pode falhar mesmo com o aplicativo offline pronto.'}</div><div class="actions"><button class="btn soft" data-action="closeBoundary">${visit.boundary.closed?'Reabrir limite':'Fechar polígono'}</button><button class="btn" data-action="undoVertex">Desvincular último vértice</button><button class="btn" data-action="importBoundary">Importar KML / GeoJSON</button></div><p class="small muted spaced">Importação: um polígono simples, sem furos. KMZ e múltiplos polígonos ficam para etapa posterior.</p></section>
<section class="card"><h2>Gravar percurso</h2><p class="small muted">${visit.route.length} posições aceitas · ${visit.routeIgnored} leituras descartadas. Percurso e limite ficam separados.</p><div class="notice">Mantenha o aplicativo visível e a tela ligada. Ao sair da tela do app ou bloquear o celular, a gravação é pausada. Não opere o celular ao dirigir.</div><div class="actions"><button class="btn ${routeId!==null?'danger':'primary'}" data-action="toggleRoute">${routeId!==null?'Parar percurso':'Iniciar percurso'}</button><button class="btn" data-action="routeBoundary">Usar último trecho como limite</button></div><p class="small muted spaced">Leituras com precisão pior que 30 m são descartadas no percurso. Vértices manuais com precisão ruim exigem confirmação e justificativa.</p><div class="divider"></div><h3>Levantamento aproximado</h3><p class="small muted">Não substitui topografia, georreferenciamento do imóvel, projeto de engenharia ou estudo de acesso à rede.</p></section></div>
<section class="card spaced"><h2>Pontos registrados (${visit.points.length})</h2>${visit.points.length?visit.points.map((p,i)=>`<div class="list-item"><div><strong>${i+1}. ${E(p.label||p.kind)}</strong><small>${E(p.kind)} · etapa ${String(p.sectionId||'—').padStart(2,'0')} · ${E(p.source)}<br>${coordsText(p)} · ${Number.isFinite(p.accuracy)?'±'+num(p.accuracy,0)+' m':'Precisão não informada'} · altitude ${Number.isFinite(p.altitude)?num(p.altitude,1)+' m':'não disponível'}<br>${fmtDate(p.createdAt)}${p.reason?'<br>Ressalva: '+E(p.reason):''}</small></div></div>`).join(''):'<div class="empty">Nenhum ponto de campo. O centro provisório não conta como ponto coletado.</div>'}</section>`;}
function evidenceCard(e){let preview='';if(/^image\/(jpeg|png|webp|gif|avif|heic)/.test(e.type))preview=`<img src="${blobURL(e.blob)}" alt="${E(e.caption||e.filename)}" loading="lazy">`;else if(e.type.startsWith('audio/'))preview=`<div class="file-icon">Nota de voz</div><audio controls preload="none" src="${blobURL(e.blob)}"></audio>`;else if(e.type.startsWith('video/'))preview=`<video controls preload="metadata" src="${blobURL(e.blob)}"></video>`;else preview='<div class="file-icon">Documento / arquivo</div>';return `<article class="evidence-card">${preview}<div class="evidence-content"><span class="pill gray">Etapa ${String(e.sectionId).padStart(2,'0')}</span><strong class="spaced">${E(e.caption||e.filename)}</strong><p class="small muted">${E(e.filename)} · ${bytes(e.size)}<br>${fmtDate(e.recordedAt)}<br>${e.position?coordsText(e.position)+' · '+E(e.position.source):'Sem GPS vinculado'}<br>${E(e.source)}</p><div class="actions"><button class="btn small-btn" data-action="downloadEvidence" data-id="${E(e.id)}">Salvar arquivo</button><button class="btn small-btn danger" data-action="deleteEvidence" data-id="${E(e.id)}">Remover</button></div></div></article>`;}
function evidenceView(){let ev=evidence.filter(e=>e.visitId===visit.id);return `<div class="page-intro"><div class="eyebrow">Fotos · documentos · vídeos · áudios</div><h1>Evidências com contexto.</h1><p class="small muted">Cada arquivo ligado à sua etapa. Sem envio para a nuvem nesta versão.</p></div><section class="card"><div class="row between"><div><h2>${ev.length} arquivos nesta vistoria</h2><span class="small muted">${bytes(ev.reduce((s,e)=>s+e.size,0))} em evidências</span></div><button class="btn primary" data-action="addEvidence" data-section="33">${icon('camera')} Nova evidência</button></div><div class="notice info">Data/hora referem-se ao registro no aplicativo, conforme o relógio do aparelho. Arquivos importados não recebem GPS automaticamente; associe um ponto quando tiver certeza da relação.</div><p class="small muted">Vídeos curtos preservam espaço. Limite de 80 MB por arquivo e 250 MB de evidências por pacote de backup nesta V2. Não apague originais antes de conferir a cópia.</p></section>${ev.length?'<div class="evidence-grid">'+ev.map(evidenceCard).join('')+'</div>':'<div class="empty">Nenhuma evidência nesta visita. Comece pelo acesso à propriedade ou pela torre anemométrica, de um lugar autorizado e seguro.</div>'}`;}
function backupView(){let ev=evidence.filter(e=>e.visitId===visit.id),m=metrics();return `<div class="page-intro"><div class="eyebrow">Segurança dos dados e entrega</div><h1>Sua coleta merece uma cópia.</h1><p class="small muted">Exportação funciona sem internet. Servidor e sincronização ainda não configurados.</p></div><div class="notice danger">O banco local não possui criptografia própria nem login nesta V2. Proteja o celular com senha. Limpar os dados do navegador, perder o aparelho ou trocar de endereço do app pode remover o acesso à coleta. Faça backup e guarde outra cópia.</div><div class="grid2"><section class="card"><h2>Pacote completo da vistoria</h2><p class="small muted">Inclui JSON para restauração, evidências originais, relatório HTML, pontos CSV, perímetro/roteiro GeoJSON e histórico operacional.</p><div class="row"><span class="pill">${ev.length} arquivos</span><span class="pill gray">${bytes(ev.reduce((s,e)=>s+e.size,0))} em evidências</span></div><label class="check"><input type="checkbox" id="encrypt-backup"> Proteger o pacote com senha (AES-GCM)</label><label class="field"><span>Senha de proteção (mínimo 10 caracteres)</span><input type="password" id="backup-password" autocomplete="new-password"><small>A senha não fica salva e não pode ser recuperada. A proteção vale para o arquivo exportado, não para o banco local.</small></label><div class="actions"><button class="btn primary" data-action="exportBackup">${icon('archive')} Gerar backup completo</button><button class="btn" data-action="restoreBackup">Restaurar backup</button></div><div class="notice">${visit.lastBackupAt?'Pacote gerado em '+fmtDate(visit.lastBackupAt)+'. '+(visit.lastBackupUpdatedAt===visit.updatedAt?'Sem alterações de conteúdo posteriores registradas.':'Há alterações após essa geração; exporte novamente.'):'Nenhum backup completo gerado.'} O navegador inicia o download; o aplicativo não consegue confirmar que você guardou uma cópia externa.</div></section>
<section class="card"><h2>Relatório e dados de campo</h2><p class="small muted">O relatório é uma organização de observações, não um parecer de viabilidade. A coleta tem ${m.issues.length} etapas que exigem atenção.</p><div class="actions"><button class="btn full soft" data-action="exportReport">Relatório HTML para leitura / impressão</button><button class="btn full" data-action="exportGeoJSON">Perímetro e pontos · GeoJSON</button><button class="btn full" data-action="exportCSV">Lista de pontos · CSV</button><button class="btn full" data-action="review">Posso sair do local?</button></div><p class="small muted spaced">No ZIP, o relatório referencia as evidências em pastas. Extraia todo o pacote antes de abri-lo. O relatório avulso apresenta o inventário, sem incorporar arquivos pesados.</p></section></div>
<section class="card spaced"><div class="row between"><h2>Preparação offline</h2><button class="btn small-btn" data-action="prepare">Preparar / verificar</button></div><div id="storage-detail" class="small muted">Consultando armazenamento…</div><p class="small spaced">Aplicativo em cache: <strong>${offlineReady?'confirmado':'a confirmar'}</strong><br>Banco: <strong>somente neste aparelho</strong><br>Sincronização com servidor: <strong>não configurada</strong><br>Mapa: <strong>croqui local; sem satélite offline</strong></p><div class="notice info">Antes da visita, abra o aplicativo instalado em modo avião, faça uma coleta de teste, feche, abra novamente e confirme que o rascunho e uma foto continuam disponíveis. Faça isso no celular que será usado em campo.</div></section>
<section class="card"><h2>Histórico operacional local</h2><p class="small muted">Registros de operação baseados no relógio do aparelho. Não são trilha inviolável nem carimbo de tempo certificado.</p>${audit.filter(a=>a.visitId===visit.id).slice(-25).reverse().map(a=>`<div class="audit-line"><strong>${E(a.action)}</strong> · ${fmtDate(a.at)}<br>${E(a.detail)}</div>`).join('')||'<p class="small muted">Sem eventos adicionais.</p>'}</section>`;}
function dialog(html){$('#dialog-body').innerHTML=html;$('#dialog').showModal();}
function pointOptions(){return '<option value="">Sem ponto vinculado</option>'+visit.points.map((p,i)=>`<option value="${E(p.id)}">${i+1}. ${E(p.label||p.kind)} · ${coordsText(p)}</option>`).join('');}
function addEvidenceDialog(section){mutable();dialog(`<h2>Nova evidência</h2><p class="small muted">Fotografe somente de locais autorizados e seguros. Não toque em equipamentos.</p><label class="field"><span>Etapa</span><select id="media-section">${CHECKLIST.map(s=>`<option value="${s.id}" ${s.id===Number(section)?'selected':''}>${String(s.id).padStart(2,'0')}. ${E(s.title)}</option>`).join('')}</select></label><label class="field"><span>Legenda</span><input id="media-caption" placeholder="Ex.: placa da torre, vista de fora da cerca"></label><label class="field"><span>Ponto previamente registrado a associar</span><select id="media-point">${pointOptions()}</select><small>Não associar um ponto sem confirmar que ele representa esta evidência.</small></label><div class="actions"><label class="btn primary" tabindex="0">Tirar foto<input id="camera-file" type="file" accept="image/*" capture="environment" hidden></label><label class="btn">Gravar vídeo<input id="video-file" type="file" accept="video/*" capture="environment" hidden></label><label class="btn">Importar arquivos<input id="media-files" type="file" multiple hidden></label><button class="btn" data-action="recordAudio" id="record-audio-btn">Gravar nota de voz</button></div><p class="small muted spaced" id="record-status">Áudio sem transcrição. Arquivos ficam no aparelho. Máximo 80 MB por arquivo.</p>`);}
function mediaSettings(){let point=visit.points.find(p=>p.id===$('#media-point')?.value);return {sectionId:Number($('#media-section')?.value||recordingSection||33),caption:$('#media-caption')?.value||'',pointId:point?.id||null,position:point?{lat:point.lat,lon:point.lon,accuracy:point.accuracy,altitude:point.altitude,gpsAt:point.gpsAt,source:point.source}:null};}
async function saveEvidence(file,source,settings){window.pendingEvidence=file;if(evidence.filter(e=>e.visitId===visit.id).reduce((n,e)=>n+e.size,0)+file.size>240*1024*1024)throw Error('Esta vistoria chegaria a mais de 240 MB de evidências. Exporte o que já coletou e crie outra vistoria para continuar, preservando todos os originais.');if(file.size>80*1024*1024)throw Error('Arquivo acima de 80 MB. Reduza a duração/tamanho ou guarde-o externamente e registre a referência.');await flush();let e={id:uid(),visitId:visit.id,...settings,filename:file.name||'audio.webm',type:file.type||'application/octet-stream',size:file.size,blob:file,source,recordedAt:now(),fileLastModified:file.lastModified?new Date(file.lastModified).toISOString():null};let row=auditEntry('Evidência adicionada',`Etapa ${e.sectionId}: ${e.filename}`);try{await Store.batch([{store:'evidence',value:e},{store:'audit',value:row}]);evidence.push(e);await scheduleSave();}catch(err){window.pendingEvidence=file;dialog('<h2>Falha ao guardar a evidência</h2><p>'+E(err.message)+'</p><p>O arquivo permanece temporariamente na memória desta aba. Salve uma cópia antes de fechar.</p><button class="btn primary" data-action="recoverEvidence">Salvar arquivo agora</button>');throw err;}}
async function mediaFiles(files,source){mutable();if(!files.length)return;let settings=mediaSettings();let count=0;busy=true;try{for(const file of files){await saveEvidence(file,source,settings);count++;}$('#dialog').close();toast(count+' arquivo(s) salvo(s) neste aparelho.');}catch(e){if($('#dialog').open)$('#dialog').close();dialog('<h2>Evidência não salva</h2><p>'+E(e.message)+'</p><p>Guarde o original antes de fechar. Os arquivos anteriores já salvos permanecem no banco.</p><button class="btn primary" data-action="recoverEvidence">Salvar cópia do arquivo atual</button>');throw e;}finally{busy=false;render();}}
async function getGPS(){if(!isSecureContext)throw Error('GPS requer endereço seguro (HTTPS) ou localhost no computador.');if(!navigator.geolocation)throw Error('Este navegador não oferece localização. Digite coordenadas com a fonte.');toast('Buscando GPS em local aberto…');return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(pos=>{const c=pos.coords;lastGPS={lat:c.latitude,lon:c.longitude,accuracy:c.accuracy,altitude:c.altitude,altitudeAccuracy:c.altitudeAccuracy,heading:c.heading,speed:c.speed,gpsAt:new Date(pos.timestamp).toISOString()};resolve(lastGPS);},err=>reject(Error(({1:'Permissão de localização negada. Autorize no navegador ou registre manualmente com fonte.',2:'Localização indisponível. Tente em céu aberto; não use o centro provisório como medição.',3:'O GPS não respondeu a tempo. Tente novamente em local aberto.'})[err.code]||err.message)),{enableHighAccuracy:true,maximumAge:0,timeout:30000}));}
function sectionForKind(kind){return ({'Vértice do limite':3,'Referência em campo':2,'Torre anemométrica':10,'Linha elétrica':18,'Subestação':20,'Acesso':8,'Obstáculo':9,'Água / drenagem':26,'Ponto alto':6,'Área solar':17,'Comunidade / edificação':27,'Parque eólico':22,'Usina solar':23,'Interferência':28})[kind]||32;}
async function addPoint(p,kind,label,sectionId,source,reason=''){if(!Core.valid(p))throw Error('Coordenadas inválidas. Use latitude/longitude em graus decimais.');mutable();if(kind==='Vértice do limite'&&visit.boundary.closed)throw Error('Reabra o polígono antes de acrescentar vértices.');let point={...p,id:uid(),kind,label:label||kind+' '+(visit.points.length+1),sectionId:sectionId||sectionForKind(kind),source,reason,createdAt:now()};visit.points.push(point);if(kind==='Vértice do limite')visit.boundary.pointIds.push(point.id);await scheduleSave('Ponto registrado',`${point.label}: ${coordsText(point)} · ${source}`);render();toast('Ponto salvo. '+(p.accuracy?'Precisão ±'+num(p.accuracy,0)+' m.':''));}
async function capturePoint(kind,label,sectionId){mutable();const p=await getGPS();let reason='';if(p.accuracy>30){if(!confirm('Precisão ruim: ±'+num(p.accuracy,0)+' m. É preferível tentar novamente. Deseja guardar mesmo assim, com ressalva?'))return;reason=prompt('Informe por que está aceitando esta precisão:')||'';if(!reason.trim())return toast('Ponto não salvo: justificativa obrigatória.',true);}await addPoint(p,kind,label,sectionId,'GPS do aparelho',reason);}
function manualPoint(kind,label,sectionId){mutable();dialog(`<h2>Coordenada informada manualmente</h2><p class="small muted">O registro será identificado como digitado, e não como leitura do aparelho.</p><form id="manual-point-form" data-kind="${E(kind)}" data-label="${E(label)}" data-section="${sectionId||''}"><div class="inline2"><label class="field"><span>Latitude</span><input name="lat" inputmode="decimal" required placeholder="Latitude decimal"></label><label class="field"><span>Longitude</span><input name="lon" inputmode="decimal" required placeholder="Longitude decimal"></label></div><label class="field"><span>Fonte das coordenadas / justificativa</span><input name="source" required placeholder="Ex.: marco indicado na planta recebida"></label><button class="btn primary" type="submit">Guardar ponto</button></form>`);}
async function closeBoundary(){mutable();if(visit.boundary.closed){if(!confirm('Reabrir o perímetro? A versão anterior será preservada no histórico da vistoria.'))return;visit.boundaryHistory.push({at:now(),...structuredClone(visit.boundary)});visit.boundary.closed=false;}else{const points=visit.boundary.pointIds.map(id=>visit.points.find(p=>p.id===id)),m=Core.polygon(points);if(m.error)throw Error(m.error);if(!confirm('Fechar estes vértices na ordem registrada? Estimativa: '+num(m.ha)+' ha. Isso não é perímetro legal nem área útil comprovada.'))return;visit.boundary.closed=true;visit.boundary.source='field';}await scheduleSave('Perímetro alterado',visit.boundary.closed?'Fechado com '+visit.boundary.pointIds.length+' vértices.':'Reaberto para conferência.');render();}
async function importBoundary(file){mutable();let text=await file.text(),points;if(file.name.toLowerCase().endsWith('.kml')){let doc=new DOMParser().parseFromString(text,'text/xml');if(doc.querySelector('parsererror'))throw Error('KML inválido.');let polys=[...doc.getElementsByTagNameNS('*','Polygon')];if(polys.length!==1||polys[0].getElementsByTagNameNS('*','innerBoundaryIs').length)throw Error('Use KML com um único polígono, sem furos.');let ring=polys[0].getElementsByTagNameNS('*','coordinates')[0]?.textContent;if(!ring)throw Error('KML sem coordenadas de polígono.');let coords=ring.trim().split(/\s+/).map(s=>s.split(',').map(Number));points=Core.parseGeoJSON({type:'Polygon',coordinates:[coords]});}else points=Core.parseGeoJSON(JSON.parse(text));if(visit.boundary.pointIds.length&&!confirm('Substituir o limite ativo pelo arquivo importado? A referência anterior e os pontos serão preservados.'))return;visit.boundaryHistory.push({at:now(),...structuredClone(visit.boundary)});let newPoints=points.map((p,i)=>({...p,id:uid(),kind:'Vértice do limite',label:'Importado '+(i+1),sectionId:3,source:'Arquivo: '+file.name,createdAt:now(),accuracy:null,altitude:null}));visit.points.push(...newPoints);visit.boundary={pointIds:newPoints.map(p=>p.id),closed:true,source:'import: '+file.name};await scheduleSave('Perímetro importado',file.name+' · '+points.length+' vértices.');render();toast('Perímetro importado. Confira a posição e a origem documental.');}
async function toggleRoute(){mutable();if(routeId!==null)return stopRoute('Interrompido pelo usuário.');if(!isSecureContext||!navigator.geolocation)throw Error('GPS exige navegador compatível em HTTPS/localhost.');routeSegment=uid();visit.routeIgnored=visit.routeIgnored||0;routeId=navigator.geolocation.watchPosition(async pos=>{if(routeBusy||routeId===null)return;routeBusy=true;try{let c=pos.coords,p={lat:c.latitude,lon:c.longitude,accuracy:c.accuracy,altitude:c.altitude,gpsAt:new Date(pos.timestamp).toISOString(),segment:routeSegment};lastGPS=p;if(c.accuracy>30){visit.routeIgnored++;}else{let prev=visit.route.at(-1);if(!prev||prev.segment!==routeSegment||Core.distance(prev,p)>=5){if(visit.route.length>=10000){await stopRoute('Limite de 10.000 pontos de percurso atingido.');return;}visit.route.push(p);}}await scheduleSave();if(view==='map')render();}catch(e){fail(e);await stopRoute('Falha de armazenamento.');}finally{routeBusy=false;}},err=>{fail(Error('Percurso pausado: '+err.message));stopRoute('Falha de GPS.');},{enableHighAccuracy:true,maximumAge:0,timeout:30000});if(navigator.wakeLock)try{wakeLock=await navigator.wakeLock.request('screen');}catch{}await scheduleSave('Percurso iniciado','Novo trecho; manter aplicativo visível.');render();toast('Gravando enquanto o aplicativo permanecer visível.');}
async function stopRoute(reason){if(routeId===null)return;navigator.geolocation.clearWatch(routeId);routeId=null;if(wakeLock){try{await wakeLock.release();}catch{}wakeLock=null;}await scheduleSave('Percurso pausado',reason);if(view==='map')render();toast('Percurso pausado. '+reason);}
async function routeBoundary(){mutable();if(routeId!==null)throw Error('Pare a gravação antes de transformar o trecho em limite.');let last=visit.route.at(-1);if(!last)throw Error('Não há percurso registrado.');let ps=visit.route.filter(p=>p.segment===last.segment);if(ps.length>3&&Core.distance(ps[0],ps.at(-1))<3)ps=ps.slice(0,-1);let m=Core.polygon(ps);if(m.error)throw Error(m.error);if(!confirm('Você percorreu de fato os limites? O último trecho será usado como polígono fechado ('+num(m.ha)+' ha), preservando o limite anterior. Não use estradas de acesso como divisa.'))return;visit.boundaryHistory.push({at:now(),...structuredClone(visit.boundary)});let newPs=ps.map((p,i)=>({...p,id:uid(),kind:'Vértice do limite',label:'Percurso '+(i+1),sectionId:3,source:'Percurso GPS convertido',createdAt:now()}));visit.points.push(...newPs);visit.boundary={pointIds:newPs.map(p=>p.id),closed:true,source:'route'};await scheduleSave('Percurso convertido em perímetro',newPs.length+' vértices; decisão explícita do usuário.');render();}
function makeGeoJSON(){let features=[];if(Core.valid(project.reference)){features.push({type:'Feature',properties:{kind:'reference_center',provisional:true,source:'Referência cadastrada pelo usuário; não medida em campo'},geometry:{type:'Point',coordinates:[project.reference.lon,project.reference.lat]}});let square=Core.square(project.reference,project.areaHa).map(p=>[p.lon,p.lat]);features.push({type:'Feature',properties:{kind:'theoretical_square',provisional:true,area_ha:project.areaHa},geometry:{type:'Polygon',coordinates:[[...square,square[0]]]}});}
for(const p of visit.points)features.push({type:'Feature',properties:{id:p.id,kind:p.kind,label:p.label,section:p.sectionId,source:p.source,accuracy_m:p.accuracy??null,altitude_m:p.altitude??null,gps_at:p.gpsAt??null,registered_at:p.createdAt,reason:p.reason||''},geometry:{type:'Point',coordinates:[p.lon,p.lat]}});
if(visit.boundary.pointIds.length){const b=visit.boundary.pointIds.map(id=>visit.points.find(p=>p.id===id)),cs=b.map(p=>[p.lon,p.lat]);if(visit.boundary.closed)features.push({type:'Feature',properties:{kind:'collected_boundary',source:visit.boundary.source,approximate:true,legal_boundary:false},geometry:{type:'Polygon',coordinates:[[...cs,cs[0]]]}});else if(cs.length>=2)features.push({type:'Feature',properties:{kind:'open_boundary',approximate:true},geometry:{type:'LineString',coordinates:cs}});}
let seg={};visit.route.forEach(p=>(seg[p.segment]??=[]).push([p.lon,p.lat]));for(const [id,cs]of Object.entries(seg))if(cs.length>=2)features.push({type:'Feature',properties:{kind:'recorded_route',segment:id},geometry:{type:'LineString',coordinates:cs}});return {type:'FeatureCollection',features};}
function makeCSV(){return Core.csv([['ordem','nome','tipo','etapa','latitude','longitude','precisao_m','altitude_m','data_gps','data_registro','origem','ressalva'],...visit.points.map((p,i)=>[i+1,p.label,p.kind,p.sectionId,p.lat,p.lon,p.accuracy,p.altitude,p.gpsAt,p.createdAt,p.source,p.reason])]);}
function evidencePath(e){return 'evidencias/etapa_'+String(e.sectionId).padStart(2,'0')+'/'+safeFile(e.id)+'_'+safeFile(e.filename);}
function reportHTML(withPaths=false){let m=metrics(),ev=evidence.filter(e=>e.visitId===visit.id),b=visit.boundary.pointIds.map(id=>visit.points.find(p=>p.id===id)),p=b.length>=3?Core.polygon(b,visit.boundary.closed):{};return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Relatório de campo · ${E(project.name)} · V2</title><style>body{font:14px/1.65 system-ui,sans-serif;color:#233b32;max-width:960px;margin:35px auto;padding:0 22px}header{border-bottom:3px solid #345641;padding-bottom:20px}h1{font-size:30px;line-height:1.2}h2{font-size:19px;margin-top:32px}h3{font-size:15px}table{width:100%;border-collapse:collapse;font-size:11px}td,th{padding:8px;border:1px solid #dbe0d7;text-align:left;overflow-wrap:anywhere}section{border:1px solid #dbe0d7;border-radius:12px;padding:20px;margin:18px 0}p{white-space:pre-wrap}.muted{color:#667168;font-size:12px}.warn{background:#faf1dc;padding:15px;border-left:3px solid #bd8c35}.photo{max-width:100%;max-height:460px}.field-map{width:100%;height:320px;display:block;background:#f0f4ec}figure{margin:12px 0;break-inside:avoid}figcaption{font-size:11px}a{color:#285540}@media print{body{margin:0;padding:0;font-size:11px}h2{break-after:avoid}section{break-inside:auto}.photo{max-height:330px}tr,figure{break-inside:avoid}}</style></head><body><header><div class="muted">PORTICALLY CAMPO · ENERGIA · V2 / v1.0.1</div><h1>Relatório de levantamento de campo</h1><h2>${E(project.name)}</h2><p>${E(visit.name)}<br>Gerado em: ${E(fmtDate(now()))}<br>Vistoria: ${E(visit.id)}</p></header><div class="warn">Pré-vistoria informativa. Não é laudo de viabilidade, projeto de engenharia, definição de limites legais ou garantia de acesso à rede. Medições, datas e relatos devem ser verificados.</div>
<h2>1. Resumo de coleta</h2><p>Área de referência: ${num(project.areaHa)} ha. Centro provisório: ${coordsText(project.reference)}.<br>Perímetro coletado: ${visit.boundary.closed?'fechado':'não fechado'}. Área aproximada: ${visit.boundary.closed&&!p.error?num(p.ha)+' ha':'não calculada'}.<br>Etapas tratadas: ${m.addressed}/40. Verificadas: ${m.verified}. Com atenção: ${m.issues.length}.<br>Evidências: ${ev.length}. Pontos: ${visit.points.length}. Posições de percurso: ${visit.route.length}.</p><p class="muted">Data/hora do aparelho não é carimbo de tempo certificado. GPS vinculado a arquivo pode ter sido associado manualmente a um ponto, conforme metadados. Altitude do aparelho não é cota topográfica certificada. Dados não foram sincronizados com servidor.</p>
<h2>2. Croqui e pontos</h2>${mapSVG()}<p class="muted">Quadrado tracejado = referência provisória; não define divisas. Geometria local aproximada; não substitui levantamento cadastral.</p><table><thead><tr><th>#</th><th>Nome / tipo</th><th>Coordenadas</th><th>Precisão e fonte</th><th>Registro</th></tr></thead><tbody>${visit.points.map((p,i)=>`<tr><td>${i+1}</td><td>${E(p.label)}<br>${E(p.kind)}</td><td>${coordsText(p)}</td><td>${p.accuracy!==null&&p.accuracy!==undefined?'±'+num(p.accuracy,0)+' m':'Não informada'}<br>${E(p.source)}${p.reason?'<br>'+E(p.reason):''}</td><td>${E(fmtDate(p.createdAt))}</td></tr>`).join('')}</tbody></table>
<h2>3. Pendências e limitações</h2>${m.issues.length?m.issues.map(s=>`<p><strong>${String(s.id).padStart(2,'0')}. ${E(s.title)}</strong> — ${E(STATUSES[answer(s.id).status])}<br>${checks(s).map(E).join(' ')} ${E(answer(s.id).reason)}</p>`).join(''):'<p>Não há lacunas de preenchimento registradas. Isso não comprova viabilidade do empreendimento.</p>'}
<h2>4. Roteiro completo e evidências</h2>${CHECKLIST.map(s=>{let a=answer(s.id);return `<section><h3>${String(s.id).padStart(2,'0')}. ${E(s.title)}</h3><p class="muted">Grupo: ${E(s.group)} · Situação: ${E(STATUSES[a.status])}</p>${s.fields.map(([k,l])=>`<p><strong>${E(l)}</strong><br>${E(a.fields[k]||'Não informado')}</p>`).join('')}${a.reason?'<p><strong>Justificativa</strong><br>'+E(a.reason)+'</p>':''}${ev.filter(e=>e.sectionId===s.id).map(e=>`<figure>${withPaths&&/^image\/(jpeg|png|webp|gif|avif)/.test(e.type)?`<img class="photo" src="${E(evidencePath(e))}" alt="${E(e.caption||e.filename)}">`:''}<figcaption><strong>${E(e.caption||e.filename)}</strong><br>${withPaths?`<a href="${E(evidencePath(e))}">${E(e.filename)}</a>`:E(e.filename)} · ${bytes(e.size)} · ${E(e.source)}<br>Registro no app: ${E(fmtDate(e.recordedAt))}<br>${e.position?coordsText(e.position)+' · '+E(e.position.source):'Sem posição vinculada'}</figcaption></figure>`).join('')}</section>`}).join('')}
<h2>5. Histórico operacional</h2>${audit.filter(a=>a.visitId===visit.id).map(a=>`<p class="muted">${E(fmtDate(a.at))} · <strong>${E(a.action)}</strong> · ${E(a.detail)}</p>`).join('')}<p class="muted">Fim do relatório · V2. Preserve o ZIP completo e suas evidências. Para análise posterior: recurso eólico, solar, conexão/escoamento, ambiental, fundiário, logística e comercial são verificações distintas.</p></body></html>`;}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),120000);}
async function hash(blob){if(!crypto.subtle)return null;const h=await crypto.subtle.digest('SHA-256',await blob.arrayBuffer());return Array.from(new Uint8Array(h),b=>b.toString(16).padStart(2,'0')).join('');}
async function encryptBlob(blob,password){if(!crypto.subtle)throw Error('Criptografia requer HTTPS/localhost e navegador compatível.');let salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));let base=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);let key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt']);let ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,await blob.arrayBuffer());return new Blob([new TextEncoder().encode('PCAMPO01'),salt,iv,ciphertext],{type:'application/octet-stream'});}
async function decryptBuffer(buffer,password){if(!crypto.subtle)throw Error('Criptografia requer HTTPS/localhost.');let b=new Uint8Array(buffer);if(b.length<53||new TextDecoder().decode(b.slice(0,8))!=='PCAMPO01')throw Error('Arquivo protegido inválido.');let base=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);let key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:b.slice(8,24),iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['decrypt']);try{return await crypto.subtle.decrypt({name:'AES-GCM',iv:b.slice(24,36)},key,b.slice(36));}catch{throw Error('Senha incorreta ou arquivo protegido corrompido.');}}
async function exportBackup(){if(busy)throw Error('Aguarde a operação atual.');if(routeId!==null)throw Error('Pause o percurso antes do backup.');if(recorder)throw Error('Pare a nota de voz antes do backup.');let persistenceIssue=null;try{await flush();}catch(e){persistenceIssue=e.message;if(!confirm('Houve falha ao salvar no banco. Gerar backup de emergência com os dados que ainda estão na memória desta aba? Não feche o aplicativo antes de conferir o arquivo.'))return;}if(busy)throw Error('Backup já está sendo preparado.');const encrypt=$('#encrypt-backup')?.checked,password=$('#backup-password')?.value||'';if(encrypt&&password.length<10)throw Error('Use uma senha com no mínimo 10 caracteres.');let ev=evidence.filter(e=>e.visitId===visit.id);if(ev.reduce((s,e)=>s+e.size,0)>250*1024*1024)throw Error('Esta vistoria excede 250 MB em evidências, limite de exportação em memória da V2. Preserve os originais e procure suporte; não apague sem cópia.');busy=true;try{toast('Preparando arquivos e conferindo integridade…');let entries=[],metadata=[];for(const e of ev){const {blob,...meta}=e;metadata.push({...meta,path:evidencePath(e),sha256:await hash(blob)});entries.push({name:evidencePath(e),data:blob});}
let exportedAt=now(),snapshot={format:'portically-campo',schema:SCHEMA,version:VERSION,semver:SEMVER,exportedAt,persistenceIssue,project:structuredClone(project),visit:structuredClone(visit),evidence:metadata,audit:structuredClone(audit.filter(a=>a.visitId===visit.id))};entries.unshift({name:'dados.json',data:JSON.stringify(snapshot,null,2)});entries.push({name:'relatorio_V2.html',data:reportHTML(true)},{name:'pontos_V2.csv',data:makeCSV()},{name:'mapa_V2.geojson',data:JSON.stringify(makeGeoJSON(),null,2)},{name:'LEIA_PRIMEIRO_V2.txt',data:'PORTICALLY CAMPO ENERGIA V2\nExtraia TODO o ZIP para abrir relatorio_V2.html com fotos.\nPara restaurar, selecione o ZIP original no aplicativo. Não recomprima.\nO relatório não é laudo de viabilidade.\nCoordenadas e perímetros do celular são aproximados.\nOs dados locais não foram sincronizados com servidor.\nHashes SHA-256, quando disponíveis, verificam arquivos; não certificam autoria ou tempo.\n'});let blob=await Core.zip(entries);if(encrypt)blob=await encryptBlob(blob,password);let filename=safeFile(project.name)+'_'+exportedAt.slice(0,10)+'_'+String((visit.exportCount||0)+1).padStart(3,'0')+'_V2.'+(encrypt?'pcampo':'zip');download(blob,filename);
visit.lastBackupAt=exportedAt;visit.lastBackupUpdatedAt=visit.updatedAt;visit.exportCount=(visit.exportCount||0)+1;let row=auditEntry('Pacote de backup gerado',filename+' · download iniciado; cópia externa não confirmada.');try{await Store.batch([{store:'visits',value:structuredClone(visit)},{store:'audit',value:row}]);}catch(e){savedStatus('Backup gerado; banco ainda com falha',true);}toast('Download iniciado. Abra o arquivo e guarde uma cópia fora do aparelho.');}finally{busy=false;if($('#backup-password'))$('#backup-password').value='';render();}}
function validateSnapshot(s,entries){if(s?.format!=='portically-campo'||s.schema!==SCHEMA)throw Error('Versão/formato de backup incompatível.');if(!s.project?.id||(s.project.reference!==null&&!Core.valid(s.project.reference))||!Number.isFinite(s.project.areaHa)||s.project.areaHa<=0)throw Error('Projeto inválido no backup.');if(!s.visit?.id||s.visit.projectId!==s.project.id||!Array.isArray(s.visit.points)||!s.visit.sections||!Array.isArray(s.visit.boundary?.pointIds)||!Array.isArray(s.visit.route))throw Error('Vistoria inválida no backup.');if(!Array.isArray(s.evidence)||!Array.isArray(s.audit))throw Error('Inventário inválido.');if(s.visit.points.some(p=>!p.id||!Core.valid(p))||new Set(s.visit.points.map(p=>p.id)).size!==s.visit.points.length)throw Error('Pontos inválidos ou duplicados.');if(s.visit.boundary.pointIds.some(id=>!s.visit.points.some(p=>p.id===id)))throw Error('Perímetro aponta para vértice ausente.');if(s.visit.route.some(p=>!Core.valid(p)))throw Error('Percurso inválido.');for(const [id,a]of Object.entries(s.visit.sections)){if(!CHECKLIST.some(c=>c.id===Number(id))||!Object.hasOwn(STATUSES,a.status)||!a.fields||typeof a.fields!=='object')throw Error('Resposta de etapa inválida.');}let ids=new Set();for(const e of s.evidence){if(ids.has(e.id)||!e.id||e.visitId!==s.visit.id||!CHECKLIST.some(c=>c.id===e.sectionId)||!entries.has(e.path)||entries.get(e.path).length!==e.size)throw Error('Evidência inválida, duplicada ou ausente: '+e.filename);ids.add(e.id);}if(s.visit.boundary.closed){let c=Core.polygon(s.visit.boundary.pointIds.map(id=>s.visit.points.find(p=>p.id===id)));if(c.error)throw Error(c.error);}return s;}
async function restoreBackup(file){if(busy)throw Error('Aguarde a operação atual.');if(readOnly)throw Error('Outra aba está editando. Feche-a antes de restaurar.');if(routeId!==null||recorder)throw Error('Pare a coleta antes de restaurar.');if(file.size>300*1024*1024)throw Error('Backup acima de 300 MB.');await flush();busy=true;try{let buffer=await file.arrayBuffer();if(file.name.endsWith('.pcampo')){let password=prompt('Senha do backup protegido:');if(password===null)return;buffer=await decryptBuffer(buffer,password);}let entries=Core.unzip(buffer);if(!entries.has('dados.json'))throw Error('O ZIP não contém dados.json do aplicativo.');let s=validateSnapshot(JSON.parse(new TextDecoder().decode(entries.get('dados.json'))),entries);if(visits.some(v=>v.id===s.visit.id))throw Error('Esta vistoria já existe neste aparelho. Nada foi sobrescrito ou duplicado. Para comparar outra versão, preserve ambas em perfis/aparelhos separados.');if(evidence.some(e=>s.evidence.some(m=>m.id===e.id)))throw Error('Há identificadores de evidência já existentes. Restauração cancelada sem sobrescrever.');let newEv=[];for(const e of s.evidence){let blob=new Blob([entries.get(e.path)],{type:e.type});if(e.sha256){const current=await hash(blob);if(!current)throw Error('HTTPS é necessário para verificar os hashes deste backup.');if(current!==e.sha256)throw Error('Falha de integridade em '+e.filename);}const {path,sha256,...meta}=e;newEv.push({...meta,blob});}
if(!confirm('Restaurar “'+s.visit.name+'” com '+newEv.length+' evidências? Não será substituída nenhuma vistoria existente.'))return;let existingProject=projects.find(p=>p.id===s.project.id);if(existingProject&&(JSON.stringify(existingProject.reference)!==JSON.stringify(s.project.reference)||existingProject.areaHa!==s.project.areaHa||existingProject.name!==s.project.name)){s.project.id=uid();s.project.name+=' · restaurado';s.visit.projectId=s.project.id;existingProject=null;}let ops=[{store:'visits',value:s.visit},...newEv.map(value=>({store:'evidence',value})),...s.audit.filter(a=>a.visitId===s.visit.id).map(value=>({store:'audit',value}))];if(!existingProject)ops.push({store:'projects',value:s.project});await Store.batch(ops);if(!existingProject)projects.push(s.project);visits.push(s.visit);evidence.push(...newEv);audit.push(...s.audit.filter(a=>a.visitId===s.visit.id));project=existingProject||s.project;visit=s.visit;await Store.put('meta',{id:'selection',projectId:project.id,visitId:visit.id});toast('Backup restaurado com integridade conferida.');}finally{busy=false;render();}}
async function refreshStorage(){if(!$('#storage-detail'))return;try{let estimate=navigator.storage?.estimate?await navigator.storage.estimate():{},pers=navigator.storage?.persisted?await navigator.storage.persisted():false;persistent=pers;if($('#storage-detail'))$('#storage-detail').textContent='Uso aproximado neste endereço: '+(estimate.usage!==undefined?bytes(estimate.usage):'não informado')+'. Cota informada pelo navegador: '+(estimate.quota?bytes(estimate.quota):'não disponível')+'. Persistência: '+(pers?'concedida; ainda faça backups.':'não garantida pelo navegador.');}catch(e){if($('#storage-detail'))$('#storage-detail').textContent='Não foi possível consultar a cota. Faça backup regularmente.';}}
async function verifyOffline(){if(!('serviceWorker' in navigator)||!isSecureContext)return false;let assets=['./','./index.html','./style.css','./core.js','./checklist.js','./store.js','./app.js','./manifest.webmanifest','./icon-192.png','./icon-512.png'];let cache=await caches.open('portically-campo-shell-v1.0.1');let found=await Promise.all(assets.map(a=>cache.match(new URL(a,location.href))));return found.every(Boolean)&&!!navigator.serviceWorker.controller;}
async function prepare(){try{if(!isSecureContext||!('serviceWorker' in navigator))throw Error('Para instalar e preparar offline, publique em HTTPS. No computador, localhost permite teste. Abrir o HTML como arquivo não prepara o app para o celular.');const reg=await navigator.serviceWorker.register('./sw.js');await Promise.race([navigator.serviceWorker.ready,new Promise((_,r)=>setTimeout(()=>r(Error('Preparação demorou. Verifique a conexão e tente novamente.')),20000))]);if(!navigator.serviceWorker.controller)await new Promise(resolve=>{navigator.serviceWorker.addEventListener('controllerchange',resolve,{once:true});setTimeout(resolve,1500);});if(navigator.storage?.persist)try{persistent=await navigator.storage.persist();}catch{}offlineReady=await verifyOffline();render();dialog(`<h2>Preparação de campo</h2><p><strong>Aplicativo em cache:</strong> ${offlineReady?'confirmado':'ainda não confirmado; recarregue com internet e repita'}.</p><p><strong>Persistência de armazenamento:</strong> ${persistent?'concedida':'não garantida pelo navegador'}.</p><p><strong>GPS / câmera:</strong> dependem do aparelho e da permissão no momento da captura.</p><p><strong>Mapa offline:</strong> croqui e dados já coletados, sem imagem de satélite.</p><div class="notice">Ainda falta um teste no seu celular: ative modo avião, capture uma foto/ponto quando possível, feche e reabra o app. Confirme o rascunho e exporte um backup.</div><p class="small muted">Leve bateria externa, combine comunicação de segurança e não apague os dados do navegador. Este app não envia informações a um servidor.</p>`);}catch(e){fail(e);}}
async function install(){if(installEvent){await installEvent.prompt();await installEvent.userChoice;installEvent=null;return;}dialog('<h2>Instalar no celular</h2><p>Depois de publicar em um endereço HTTPS, abra esse endereço no navegador do celular, ainda com internet.</p><p>No menu do navegador, procure <strong>Instalar aplicativo</strong> ou <strong>Adicionar à tela inicial</strong>. O nome e a disponibilidade dependem do navegador.</p><p>Depois toque em <strong>Preparar / verificar</strong> e faça o teste em modo avião.</p><div class="notice">Este pacote não é APK. Abertura local de index.html não substitui a instalação a partir de HTTPS.</div>');}
function review(){const m=metrics(),critical=m.issues.filter(s=>s.critical),other=m.issues.filter(s=>!s.critical);dialog(`<h2>Posso sair do local?</h2><p class="small muted">A conferência indica lacunas, não impede sua saída. Segurança tem prioridade.</p><div class="row"><span class="pill">${m.addressed}/40 tratadas</span><span class="pill warn">${critical.length} prioritárias com atenção</span></div>${[...critical,...other].map(s=>`<div class="list-item"><div><strong>${String(s.id).padStart(2,'0')}. ${E(s.title)}</strong><small>${checks(s).map(E).join(' ')}${answer(s.id).reason?' Motivo: '+E(answer(s.id).reason):''}${['notfound','later'].includes(answer(s.id).status)?' Necessita verificação posterior.':''}</small></div><button class="btn small-btn" data-action="openSection" data-section="${s.id}">Ver</button></div>`).join('')||'<div class="notice info">Todas as etapas foram tratadas. Confira a legibilidade das evidências e o backup; isso não atesta a viabilidade do empreendimento.</div>'}<div class="notice">Backup completo ${visit.lastBackupAt?'gerado em '+fmtDate(visit.lastBackupAt):'ainda não gerado'}. Confirme o arquivo salvo antes de apagar qualquer coisa.</div>`);}
function updateSectionStatus(id){const s=CHECKLIST.find(s=>s.id===Number(id)),a=answer(id),errors=checks(s);let tag=$('#tag-'+id);if(tag){tag.textContent=STATUSES[a.status]+(a.status==='done'&&errors.length?' · incompleta':'');tag.className='pill '+(errors.length?'gray':a.status==='done'?'':'warn');let dot=tag.previousElementSibling;dot.className='status-dot '+(errors.length?'':a.status==='done'?'ok':'attention');}let area=$('#validation-'+id);if(area)area.innerHTML=errors.length?'<div class="errors">'+errors.map(E).join('<br>')+'</div>':'<p class="small">Etapa tratada. '+(a.status==='done'?'Campos e evidências mínimas presentes.':'Justificativa registrada; não equivale a dado verificado.')+'</p>';}
async function closeVisit(){mutable();if(routeId!==null||recorder)throw Error('Pare o percurso e a gravação de voz antes de encerrar.');let m=metrics();if(m.pending)return review();if(!confirm('Encerrar esta coleta '+(m.issues.length?'com '+m.issues.length+' etapas para verificação posterior':'com todas as etapas tratadas')+'? Você poderá reabri-la e manterá o histórico.'))return;visit.status=m.issues.length?'closed-pending':'closed';visit.closedAt=now();await scheduleSave('Vistoria encerrada',visit.status+'; não atesta viabilidade.');render();}
async function recordAudio(){if(recorder){recorder.stop();return;}mutable();if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Gravação de voz indisponível neste navegador. Anexe um áudio do gravador do celular ou use texto.');let settings=mediaSettings();recordingSection=settings.sectionId;recordingChunks=[];recordingStarted=now();recorderStream=await navigator.mediaDevices.getUserMedia({audio:true});let type=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(recorderStream,type?{mimeType:type}:undefined);let current=recorder;current.ondataavailable=e=>{if(e.data.size)recordingChunks.push(e.data);};current.onstop=async()=>{clearTimeout(recordingTimeout);recorderStream?.getTracks().forEach(t=>t.stop());recorderStream=null;recorder=null;let blob=new Blob(recordingChunks,{type:current.mimeType});recordingChunks=[];let ext=current.mimeType.includes('mp4')?'m4a':'webm';let file=new File([blob],'Nota_voz_'+recordingStarted.replace(/[:.]/g,'-')+'.'+ext,{type:blob.type});try{await saveEvidence(file,'Nota de voz gravada no app',settings);$('#dialog').close();render();toast('Áudio salvo. Transcrição não incluída.');}catch(e){fail(e);}};current.onerror=()=>{recorderStream?.getTracks().forEach(t=>t.stop());toast('Falha no gravador. Verifique a permissão e use texto se necessário.',true);};current.start(1000);recordingTimeout=setTimeout(()=>{if(recorder?.state==='recording')recorder.stop();},120000);$('#record-audio-btn').textContent='Parar e salvar áudio';$('#record-status').textContent='Gravando… limite de 2 minutos. Não feche esta tela.';}
function projectDialog(isNew=false){if(readOnly)throw Error('Outra aba está editando o aplicativo.');dialog(`<h2>${isNew?'Outra propriedade':'Dados do projeto'}</h2><form id="project-form" data-new="${isNew?'1':'0'}"><label class="field"><span>Nome</span><input name="name" required value="${isNew?'':E(project.name)}"></label><label class="field"><span>Área de referência em hectares</span><input name="area" inputmode="decimal" required value="${isNew?'':project.areaHa}"></label><div class="inline2"><label class="field"><span>Latitude central de referência</span><input name="lat" inputmode="decimal" value="${isNew?'':project.reference?.lat??''}"></label><label class="field"><span>Longitude central de referência</span><input name="lon" inputmode="decimal" value="${isNew?'':project.reference?.lon??''}"></label></div><label class="field"><span>Fonte / observação</span><textarea name="note">${isNew?'':E(project.note||'')}</textarea></label><p class="small muted">A localização é opcional agora: deixe os dois campos vazios para preencher depois. Coordenadas e documentos ficam neste aparelho, não no site público. Referência não comprova divisas ou titularidade.</p><button class="btn primary" type="submit">Salvar projeto</button></form>`);}
async function rememberSelection(){await Store.put('meta',{id:'selection',projectId:project.id,visitId:visit.id});}
async function openSection(id){if($('#dialog').open)$('#dialog').close();filter='all';view='checklist';await flush();render();let d=$('#section-'+id);if(d){d.open=true;d.scrollIntoView({behavior:'smooth',block:'start'});}}
const ACTIONS={
 prepare,install,review,closeVisit,exportBackup,
 newVisit:async()=>{if(readOnly)throw Error('Outra aba está editando.');if(routeId!==null||recorder)throw Error('Pare a coleta antes de mudar de vistoria.');let name=prompt('Nome da nova vistoria:', 'Vistoria '+new Date().toLocaleDateString('pt-BR'));if(!name?.trim())return;await flush();visit=newVisit(project.id,name.trim());await Store.put('visits',visit);visits.push(visit);await rememberSelection();view='home';render();},
 newProject:()=>projectDialog(true),editProject:()=>projectDialog(false),
 addEvidence:b=>addEvidenceDialog(Number(b.dataset.section||33)),
 nextSection:b=>openSection(Math.min(40,Number(b.dataset.section)+1)),openSection:b=>openSection(Number(b.dataset.section)),
 gpsSection:b=>{let id=Number(b.dataset.section),s=CHECKLIST.find(s=>s.id===id),kind=id===3?'Vértice do limite':[10,11,12,13,14,15].includes(id)?'Torre anemométrica':id===18||id===19?'Linha elétrica':id===20?'Subestação':'Outro';return capturePoint(kind,s.title,id);},
 capturePoint:()=>capturePoint($('#point-kind').value,$('#point-label').value),manualPoint:()=>manualPoint($('#point-kind').value,$('#point-label').value),
 zoomIn:()=>{mapZoom=Math.min(5,mapZoom*1.4);render();},zoomOut:()=>{mapZoom=Math.max(.3,mapZoom/1.4);render();},zoomFit:()=>{mapZoom=1;render();},
 closeBoundary,
 undoVertex:async()=>{mutable();if(visit.boundary.closed)throw Error('Reabra o polígono antes de editar os vértices.');if(!visit.boundary.pointIds.length)return;if(!confirm('Retirar o último ponto da sequência de limites? O ponto continuará no inventário da vistoria.'))return;let id=visit.boundary.pointIds.pop();await scheduleSave('Vértice desvinculado',id+'; ponto preservado.');render();},
 importBoundary:()=>{mutable();$('#perimeter-file').click();},toggleRoute,routeBoundary,
 externalMap:()=>{const p=Core.valid(project.reference)?project.reference:visit.points.find(Core.valid);if(!p)throw Error('Cadastre a referência ou um ponto GPS primeiro.');if(!confirm('Abrir o Google Maps? As coordenadas deste ponto serão compartilhadas com esse serviço externo. Ele depende de internet.'))return;const url='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.lat+','+p.lon);window.open(url,'_blank','noopener,noreferrer');},
 downloadEvidence:b=>{let e=evidence.find(e=>e.id===b.dataset.id);if(e)download(e.blob,safeFile(e.filename));},
 deleteEvidence:async b=>{mutable();let e=evidence.find(e=>e.id===b.dataset.id);if(!e)return;if(!confirm('Remover '+e.filename+' do banco local? Faça backup primeiro. Esta ação não remove cópias já exportadas.'))return;let row=auditEntry('Evidência removida',e.filename);await Store.batch([{store:'evidence',delete:true,key:e.id},{store:'audit',value:row}]);evidence=evidence.filter(x=>x.id!==e.id);await scheduleSave();render();},
 recordAudio,recoverEvidence:()=>{if(window.pendingEvidence)download(window.pendingEvidence,safeFile(window.pendingEvidence.name||'captura_V2.webm'));},
 exportReport:async()=>{await flush();download(new Blob([reportHTML(false)],{type:'text/html;charset=utf-8'}),'Relatorio_'+safeFile(project.name)+'_V2.html');toast('Relatório gerado. Evidências originais acompanham o backup completo.');},
 exportGeoJSON:async()=>{await flush();download(new Blob([JSON.stringify(makeGeoJSON(),null,2)],{type:'application/geo+json'}),'Mapa_'+safeFile(project.name)+'_V2.geojson');},
 exportCSV:async()=>{await flush();download(new Blob([makeCSV()],{type:'text/csv;charset=utf-8'}),'Pontos_'+safeFile(project.name)+'_V2.csv');},
 restoreBackup:()=>$('#restore-file').click(),
 reopen:async()=>{if(readOnly)throw Error('Outra aba está editando.');if(!confirm('Reabrir esta vistoria para alteração? A operação será registrada.'))return;visit.status='draft';await scheduleSave('Vistoria reaberta','Reabertura explícita.');render();}
};
document.addEventListener('click',async ev=>{const nav=ev.target.closest('[data-nav]');if(nav){ev.preventDefault();return go(nav.dataset.nav);}const btn=ev.target.closest('[data-action]');if(!btn)return;const name=btn.dataset.action;if(!ACTIONS[name])return;try{if(busy)throw Error('Aguarde a operação atual.');await ACTIONS[name](btn);}catch(e){fail(e);}});
document.addEventListener('input',ev=>{let el=ev.target;if(!el.matches('[data-field],[data-reason]'))return;try{mutable();let id=Number(el.dataset.section);visit.sections[id]??={status:'pending',reason:'',fields:{}};if(el.hasAttribute('data-reason'))visit.sections[id].reason=el.value;else visit.sections[id].fields[el.dataset.field]=el.value;scheduleSave();updateSectionStatus(id);}catch(e){fail(e);render();}});
document.addEventListener('change',async ev=>{let el=ev.target;try{
if(el.matches('[data-status]')){mutable();let id=Number(el.dataset.section);visit.sections[id]??={status:'pending',reason:'',fields:{}};visit.sections[id].status=el.value;await scheduleSave('Situação da etapa alterada','Etapa '+id+': '+STATUSES[el.value]);updateSectionStatus(id);}
else if(el.id==='check-filter'){filter=el.value;render();}
else if(el.id==='project-select'||el.id==='visit-select'){if(routeId!==null||recorder)throw Error('Pare a gravação/percurso antes de trocar a vistoria.');await flush();if(el.id==='project-select'){project=projects.find(p=>p.id===el.value);visit=visits.filter(v=>v.projectId===project.id).at(-1);}else visit=visits.find(v=>v.id===el.value);if(!readOnly)await rememberSelection();render();}
else if(el.id==='perimeter-file'){let f=el.files[0];el.value='';if(f)await importBoundary(f);}
else if(el.id==='restore-file'){let f=el.files[0];el.value='';if(f)await restoreBackup(f);}
else if(['media-files','camera-file','video-file'].includes(el.id)){const files=[...el.files];let source=el.id==='media-files'?'Arquivo importado (data original não verificada)':el.id==='camera-file'?'Captura solicitada à câmera (origem depende do navegador)':'Vídeo solicitado à câmera (origem depende do navegador)';await mediaFiles(files,source);}
}catch(e){fail(e);if(el.id==='project-select'||el.id==='visit-select')render();}});
document.addEventListener('submit',async ev=>{const form=ev.target;if(!['manual-point-form','project-form'].includes(form.id))return;ev.preventDefault();try{const d=Object.fromEntries(new FormData(form)),parse=s=>Number(String(s).trim().replace(',','.'));if(form.id==='manual-point-form'){const p={lat:parse(d.lat),lon:parse(d.lon),accuracy:null,altitude:null,gpsAt:null};if(!String(d.source).trim())throw Error('Informe a fonte das coordenadas.');await addPoint(p,form.dataset.kind,form.dataset.label,Number(form.dataset.section)||undefined,'Digitado: '+d.source);$('#dialog').close();}else{if(readOnly||busy)throw Error('Edição indisponível nesta aba.');if(routeId!==null||recorder)throw Error('Pare a coleta antes de alterar o projeto.');const hasLat=String(d.lat).trim()!=='',hasLon=String(d.lon).trim()!=='';if(hasLat!==hasLon)throw Error('Preencha latitude e longitude juntas, ou deixe ambas vazias.');let ref=hasLat?{lat:parse(d.lat),lon:parse(d.lon)}:null;let area=parse(d.area);if((ref!==null&&!Core.valid(ref))||!Number.isFinite(area)||area<=0||area>500000)throw Error('Confira coordenadas e área (entre 0 e 500.000 ha).');if(!d.name.trim())throw Error('Informe o nome do projeto.');await flush();if(form.dataset.new==='1'){project={id:uid(),name:d.name.trim(),areaHa:area,reference:ref,note:d.note,createdAt:now(),updatedAt:now()};visit=newVisit(project.id);await Store.batch([{store:'projects',value:project},{store:'visits',value:visit}]);projects.push(project);visits.push(visit);}else{project.name=d.name.trim();project.areaHa=area;project.reference=ref;project.note=d.note;project.updatedAt=now();await Store.put('projects',structuredClone(project));await scheduleSave('Projeto editado','Nome/área/ponto de referência atualizados. Referência não é divisa.');}await rememberSelection();$('#dialog').close();view='home';render();}}
catch(e){fail(e);}});
$('#dialog-close').onclick=()=>{if(recorder){if(confirm('Parar e salvar a nota de voz antes de fechar?'))recorder.stop();return;}$('#dialog').close();};
$('#dialog').addEventListener('cancel',e=>{if(recorder)e.preventDefault();});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;});
window.addEventListener('online',()=>{connection();toast('Rede detectada. Dados continuam locais; servidor não configurado.');});
window.addEventListener('offline',()=>{connection();toast('Sem rede. Continue coletando e faça backup no aparelho.');});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){if(routeId!==null)stopRoute('Aplicativo fora de primeiro plano. Retome manualmente.').catch(fail);if(recorder?.state==='recording')recorder.stop();}});
window.addEventListener('beforeunload',ev=>{if(recorder||routeId!==null||busy||saveError){ev.preventDefault();ev.returnValue='';}});
window.addEventListener('error',ev=>{console.error(ev.error);});
async function start(){connection();try{await Store.open();if(navigator.locks){await new Promise(resolve=>{navigator.locks.request('portically-campo-writer-v1',{ifAvailable:true},async lock=>{if(!lock){readOnly=true;resolve();return;}resolve();await new Promise(r=>writerRelease=r);}).catch(()=>resolve());});}
projects=await Store.all('projects');visits=await Store.all('visits');evidence=await Store.all('evidence');audit=(await Store.all('audit')).sort((a,b)=>a.at.localeCompare(b.at));
if(!projects.length){if(readOnly){$('#main').innerHTML='<div class="notice">Outra aba está iniciando o aplicativo. Feche-a e recarregue esta.</div>';return;}project={id:uid(),name:'Minha área em estudo',areaHa:600,reference:null,note:'Área provisória. Informe a localização em Editar projeto. Dados permanecem neste aparelho; titularidade e perímetro ainda precisam de conferência.',createdAt:now(),updatedAt:now()};visit=newVisit(project.id,'Primeiro levantamento');projects.push(project);visits.push(visit);await Store.batch([{store:'projects',value:project},{store:'visits',value:visit}]);}
const selection=await Store.get('meta','selection');project=projects.find(p=>p.id===selection?.projectId)||projects[0];visit=visits.find(v=>v.id===selection?.visitId&&v.projectId===project.id)||visits.find(v=>v.projectId===project.id);if(!visit)throw Error('Projeto sem vistoria. Restaure um backup válido.');dbReady=true;savedStatus(readOnly?'Somente leitura nesta aba':'Dados locais carregados');if('serviceWorker' in navigator&&isSecureContext){try{await navigator.serviceWorker.register('./sw.js');offlineReady=await verifyOffline();navigator.serviceWorker.addEventListener('controllerchange',async()=>{offlineReady=await verifyOffline();if(view==='home')render();});}catch(err){console.warn('Preparação offline pendente:',err);}}render();}catch(e){$('#main').innerHTML='<div class="notice danger"><h2>Não foi possível abrir o banco local</h2><p>'+E(e.message)+'</p><p>Não colete dados nesta aba até corrigir o erro. Verifique espaço e permissões. Navegação privada pode limitar o armazenamento.</p></div>';savedStatus('Armazenamento indisponível',true);console.error(e);}}
start();
